#pragma once

//These are a bunch of defines used for storing/chacking input values

#define FOREWARD_PRESSED 0b1
#define FOREWARD_RELEASED FOREWARD_PRESSED ^ UINT_MAX
#define BACKWARD_PRESSED 0b10
#define BACKWARD_RELEASED BACKWARD_PRESSED ^ UINT_MAX
#define LEFT_PRESSED 0b100
#define LEFT_RELEASED LEFT_PRESSED ^ UINT_MAX
#define RIGHT_PRESSED 0b1000
#define RIGHT_RELEASED RIGHT_PRESSED ^ UINT_MAX
#define USE_PRESSED 0b10000
#define USE_RELEASED USE_PRESSED ^ UINT_MAX